# config
#
# spring boot connection
#
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web-sale-security-equipment?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: sapassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
        format_sql: true
    show-sql: true
#  mail:
#    host: stmp.gmail.com
#    password: 123abbddeagasgswg
#    port: 587
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    username: dohuyhoang.iuh.k15@gmail.com
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 58807738435-6ghspa22i6jb37mldcocvd0se2fsgg6l.apps.googleusercontent.com
            client-secret: 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
            redirect-uri-template: http://localhost:8080/login/oauth2/code/google
            client-authentication: basic
            authorization-grant-type: authorization_code
            scope:
            - email
            - profile
          facebook:
            client-id: 5016197031777780
            client-secret: a7e76c1866c16b20ce32c33038ee7194
            scope:
              - email
              - public_profile
